# Generated by Django 4.2.6 on 2023-10-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdleGameV2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreboard',
            name='description',
        ),
        migrations.RemoveField(
            model_name='scoreboard',
            name='name',
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='cookies',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
