# Generated by Django 4.2.6 on 2023-10-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdleGameV2', '0002_remove_scoreboard_description_remove_scoreboard_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='cookies',
            field=models.IntegerField(null=True),
        ),
    ]
