# Generated by Django 4.2.6 on 2023-10-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdleGameV2', '0003_alter_scoreboard_cookies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreboard',
            name='cookies',
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='description',
            field=models.CharField(default=10, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='name',
            field=models.CharField(default=10, max_length=20),
            preserve_default=False,
        ),
    ]
